name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 21
          check-latest: true
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm test
